### ISSUE TITLE
UX/UI Design

### ISSUE THREAD

**Issue by lucasb** [Fleeg/fleeg-platform#1]
The project was lunched focusing to release some functionalities, but UX and UI is important too. Although this issue is to discuss about that, and we appreciate any design suggestion.

**Comment by lucasb** [comment]
To understand more about project propose, you can see our page with features overview: https://github.com/Fleeg/fleeg-platform/wiki/Features

**Comment by lucasb** [comment]
Current work: https://github.com/Fleeg/fleeg-ux-ui

**Comment by gitarno** [comment]
👍

**Comment by lucasb** [comment]
It's done on this new repository: https://github.com/Fleeg/fleeg-webapp and should be envolve there.
